#!/bin/bash

# Requirements
#
# apt-get install pandoc
# apt-get install texlive-xetex
# apt-get install pdftk-java

echo create tmp directory with sources: src.pdf
rm -rf    src.pdf
cp -R src src.pdf
cd        src.pdf

mkdir     tmp

echo create tmp direcetory for images
for DIR in $(find ../src -type d -name images); do cp -R $DIR .; done

echo create book.pdf

FILES=""

for FILE in $(python ../list_files.py)
do
	SRC=${FILE}.md
	DST=$(basename $SRC .md).pdf

	printf "create %-32s from %s\n" ${DST} ${SRC}
	pandoc ${SRC} --latex-engine=xelatex -o tmp/${DST}

	FILES="$FILES tmp/$DST"
done

echo create slic3r-book.pdf
pdftk $FILES cat output slic3r-book.pdf

rm -rf tmp
